import 'package:flutter/material.dart';

class ExhibitorData {
  final String name;
  final String logo;
  final List<String> industries;
  final String booth;
  final bool isHiring;
  final bool hasRoles;
  final Color? color;

  ExhibitorData({
    required this.name,
    required this.logo,
    required this.industries,
    required this.booth,
    this.isHiring = false,
    this.hasRoles = false,
    this.color,
  });
}

final List<ExhibitorData> exhibitors = [
  ExhibitorData(
    name: 'PETRONAS',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'A1',
    color: Colors.blue[100],
  ),
  ExhibitorData(
    name: 'ORSTED MALAYSIA',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'A2',
    color: Colors.blue[100],
  ),
  ExhibitorData(
    name: 'SLB',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'A3',
    color: Colors.blue[100],
  ),
  ExhibitorData(
    name: 'EXXONMOBIL MALAYSIA',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'A4',
    color: Colors.blue[100],
  ),
  ExhibitorData(
    name: 'MALAYSIA MARINE AND HEAVY ENGINEERING HOLDINGS BERHAD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'A5',
    color: Colors.blue[100],
  ),
  ExhibitorData(
    name: 'BOSCH MALAYSIA',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'A6',
    color: Colors.blue[100],
  ),
  ExhibitorData(
    name: 'HUAWEI TECHNOLOGIES (M) SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B1',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'SHELL',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B2',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'COCA-COLA BEVERAGES SINGAPORE, MALAYSIA & BRUNEI',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B3',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'HALLIBURTON',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B4',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'BBS AUTOMATION PENANG SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B5',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'INTEL MICROELECTRONICS (M) SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B6',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'E&P O&M SERVICES SDN BHD (EPOMS)',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B7',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'BAKER HUGHES',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B8',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'GREATECH',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B9',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'WEHAYA SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'B10',
    color: Colors.orange[100],
  ),
  ExhibitorData(
    name: 'SCHMIDT ABRASIVE BLASTING',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C1',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'SYNTHOMER',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C2',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'ALLIANZ MALAYSIA BERHAD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C3',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'FINEXUS SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C4',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'I-CHEM SOLUTION SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C5',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'CAPITAL DYNAMICS',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C6',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'DINDINGS TYSON SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C7',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'SUNWAY CONSTRUCTION SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C8',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'MICRON MALAYSIA',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C9',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'POLYGON SYNERGY VENTURES SDN. BHD.',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C10',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'VEOLIA WATER TECHNOLOGIES SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C11',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'PwC MALAYSIA',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C12',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'DAIKIN MALAYSIA',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C13',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'UNIT CONCEPT',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C14',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'TALENTCORP GROUP',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C15',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'PENGERANG GAS SOLUTIONS SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C16',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'KUALA LUMPUR KEPONG BERHAD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C17',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'INPROCESS',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C18',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'HOVID BERHAD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C19',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'SCHNEIDER ELECTRIC',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C20',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'VANCE BIOENERGY SDN. BHD.',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C21',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'EMERSON PROCESS MANAGEMENT (MALAYSIA) SDN. BHD.',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C22',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'PROTON',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C23',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'GRADUAN',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C24',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'HRD CORP PLACEMENT CENTRE',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C25',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'MARii',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C26',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'PERKESO',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C27',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'TT VISION TECHNOLOGIES SDN BHD.',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C28',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'NXP SEMICONDUCTORS',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C29',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'AVERY DENNISON SMARTRAC',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C30',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'HEWLETT PACKARD ENTERPRISE',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C31',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'PUBLIC BANK',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C32',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'AMERICAN AIR FILTER',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C33',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'KERETAPI TANAH MELAYU BERHAD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C34',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'HONEYWELL ENGINEERING SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C35',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'JURIS TECHNOLOGIES',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C36',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'WEI DAT STEEL WIRE SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C37',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'RHB BANKING GROUP',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C38',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'PETRON MALAYSIA',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C39',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'YOKOGAWA MALAYSIA',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C40',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'FPT SOFTWARE',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C41',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'REINHAUSEN',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C42',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'YTL CONSTRUCTION',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C43',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'KLAY EnerSol',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C44',
    color: Colors.pink[100],
  ),
  ExhibitorData(
    name: 'MURATA ELECTRONICS (M) SDN BHD',
    logo: 'https://placehold.jp/150x150.png',
    industries: [],
    booth: 'C45',
    color: Colors.pink[100],
  ),
];
